heat_template_version: 2015-10-15

description: >
  Example of using monasca resources for auto-scale testing. In this template,
  sample scale-group is created with given nova instance to auto-scale
  when cpu utilization varies between 15 to 50 percent for 3 times consequently.
parameters:
  flavor:
    type: string
    description: Flavor for the instances to be created
    default: m1.nano
  image:
    type: string
    description: Name or ID of the image to use for the instances.
    default: cirros-0.4.0-x86_64-disk

resources:
  group:
    type:  ##FILLHERE##
    properties:
      cooldown: 60
      desired_capacity: ##FILLHERE##
      max_size: ##FILLHERE##
      min_size: 1
      resource:
        type: OS::Nova::Server
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          metadata : {"scale_group": {get_param: "OS::stack_id"}}
          networks:
          - network: private
          security_groups:
          - testvm

#  scale_up_policy:
#
#  scale_down_policy:
#
#  up_notification:
#    type:
#    properties:
#      type:
#      address: {get_attr: [scale_up_policy, alarm_url]}
#
#  down_notification:
#    type:
#    properties:
#      type:
#      address: {get_attr: [scale_down_policy, alarm_url]}
#
#  cpu_alarm_high:
#     ##FILLHERE##
#        str_replace:
#          template: avg(cpu.utilization_perc{scale_group=##FILLHERE##}) > 50 times 3
#          params:
#            ##FILLHERE##: {get_param: "OS::stack_id"}
#
#  cpu_alarm_low:
#     ##FILLHERE##
#        str_replace:
#          template: avg(cpu.utilization_perc{scale_group=##FILLHERE##}) < 15 times 3
#          params:
#            ##FILLHERE##: {get_param: "OS::stack_id"}
